import type { Metadata } from "next";
import "./globals.css";
import Footer from "./_components/footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">{children} <Toaster/></body>
      <footer className="dark"><Footer/></footer>
    </html>
  );
}
